version: '3'

services:
  lab_2_2:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PORT: "5000"
    ports:
    - "5000:5000"
  db:
    image: postgres:15.4-alpine3.18
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: admin
      POSTGRES_DB: database
    ports:
      - "5432:5432"
