FROM python:3.11.3-slim-bullseye(or other version you use)


WORKDIR /app


COPY requirements.txt .


RUN python -m pip install -r requirements.txt


COPY . /app


CMD flask --app <your app name> run -h 0.0.0.0 -p $PORT
